# Generated by Django 5.0.3 on 2024-03-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novel', '小説'), ('essay', 'エッセイ'), ('practical', '実用書')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
