# Generated by Django 5.0.3 on 2024-03-23 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readingdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
