# Generated by Django 5.0.3 on 2024-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('novel', '小説'), ('essay', 'エッセイ'), ('practical', '実用書')], max_length=100, null=True),
        ),
    ]
